### ISSUE TITLE
use_scm_version = True

### ISSUE THREAD

**Issue by KOLANICH** [kennethreitz/setup.py#21]
https://github.com/pypa/setuptools_scm

**Comment by kennethreitz** [comment]
Considered that, but my concerns are about tarballs downloaded from github.

**Comment by webknjaz** [comment]
I'd disallow tarballs with git repo, regarding GitHub Releases, it is possible to make setuptools-scm generate a python module containing version assignment. If one downloads some invalid version, raise friendly exception explaining what is wrong and how to do it right.

**Comment by kennethreitz** [comment]
I'm going to stay away from setuptools_scm for this. It looks super dope, but 

1. I've never used it (not against trying it)
2. I really want people to be able to install tarballs from GitHub.

**Comment by webknjaz** [comment]
JFYI, there's actually an additional distribution solving (2): https://pypi.python.org/pypi/setuptools_scm_git_archive
