### ISSUE TITLE
Deprecated API?

### ISSUE THREAD

**Issue by sieben** [kennethreitz/setup.py#24]
I'm using the following setup.py file: https://gist.github.com/sieben/e7003fab39c201b902f9442d2b954a04 

When I use the following command:

$ python2 setup.py publish 
$ python3 setup.py publish 

I get the following error:

HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html) for url: https://pypi.python.org/pypi

**Comment by kennethreitz** [comment]
Use the updated version.
