### ISSUE TITLE
How about automatically updating version?

### ISSUE THREAD

**Issue by lk-geimfari** [kennethreitz/setup.py#28]
How about custom command `versioner` for `setup.py` which automatically increment version string in `__version__.py`.

How it's works:
![image](https://user-images.githubusercontent.com/15812620/30858643-347d5d50-a2c9-11e7-899e-159939f9f682.png)

What do you thinks about it? It's good practice or maybe it's bad idea for some reasons?

Small function which increment version in string format: [here](https://gist.github.com/lk-geimfari/3b888a665670c83d1619645fca509dad)
Complete command is available [here](https://github.com/lk-geimfari/mimesis/blob/master/setup.py#L179).

**Comment by kennethreitz** [comment]
code bloat

**Comment by NargiT** [comment]
What about CI ? Nowadays most of the application are released from a CI and not from my local machine, so I do not need to bother with enterprise configuration.

**Comment by timofurrer** [comment]
... and there is also setuptools_scm which might be a good choice for you.

**Comment by florisla** [comment]
There is also `bump2version` which follows a different approach from setuptools_scm.

It's not perfect but it works very well.
