### ISSUE TITLE
PyPI upload appears to require 'wheel' installation

### ISSUE THREAD

**Issue by jrmontag** [kennethreitz/setup.py#29]
When attempting to upload a new project (using Python 3.5.1 in a virtualenv) to PyPI using the README (and inline comment) steps, the ``$ python setup.py upload`` command failed with the error message below. 

```
$ python setup.py upload
running upload
Removing previous builds…
Building Source and Wheel (universal) distribution…
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
Uploading the package to PyPi via Twine…
ValueError: Cannot find file (or expand pattern): 'dist/*'
```

An SO entry led me to running ``$ pip install wheel`` and following that step, the previous ``upload`` command did work as expected. 

Would it be useful to open a PR with the [example pip command](https://github.com/kennethreitz/setup.py/blob/4b4eb9d46a0f14d52355a970a3a41f3d9bc137bb/setup.py#L5) updated to include ``wheel`` after twine?

**Comment by dskrad** [comment]
wheel is automatically installed in my virtualenv
```
$ virtualenv -p python3 venv
Running virtualenv with interpreter python3
New python executable in venv/bin/python3
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.

$ pip list
pip (9.0.1)
setuptools (38.4.0)
wheel (0.30.0)

$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
Why is wheel missing from your virtualenv?
