### ISSUE TITLE
Version bump as part of setup.py?

### ISSUE THREAD

**Issue by kootenpv** [kennethreitz/setup.py#35]
How can we do a nice version bump for major/minor/micro changes?

It might be nice as an extra possible command in `setup.py`? Would this be possible?

Or do you think it more fits in `pipenv`?

**Comment by kootenpv** [comment]
I'm waiting with creating a project in order to use the recommendation concerning "how to do version bumps" :) I think using the setup.py like this without version bump might be worse than a Pipfile?

**Comment by imiric** [comment]
If you don't mind managing your versions in Git, there's a [setuptools SCM plugin](https://github.com/pypa/setuptools_scm) that simplifies this integration, and allows you to avoid version bump commits entirely.

**Comment by florisla** [comment]
Another alternative is using [bump2version](https://pypi.org/project/bump2version/).  It's being used in the wild, see for example https://github.com/PyCQA/pydocstyle/blob/master/.bumpversion.cfg .

I don't think tagging and version bumping should be configured in `setup.py` -- it should just describe your package and allow it to be built.
