### ISSUE TITLE
How to include additional packages in setup.py

### ISSUE THREAD

**Issue by niranjanreddy891** [kennethreitz/setup.py#36]
I am using Python-2.7 with  windows-7 64 bit. Can anyone guide me how to modify setup.py. I want to add few packages in setup.py. I installed python-2.7 through anaconda. Thanks in advance

**Comment by florisla** [comment]
Hi,

This is not the correct place to ask general Python packaging questions.

Please read this:
https://packaging.python.org/tutorials/packaging-projects/
and take a look at `setuptools.find_packages()`.

**Comment by Projjol** [comment]
Closing this as explained by @florisla in the comment above that this is not an issue.
