### ISSUE TITLE
Support rendering project description from Markdown 

### ISSUE THREAD

**Issue by wigging** [kennethreitz/setup.py#38]
As detailed [here](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) please update `setup.py` to support rendering the project description from Markdown.

**Comment by mschwager** [comment]
I recently did this with the following commit: https://github.com/mschwager/fierce/commit/23af95f39316f2b4e810972d35ff5c84cc13703c, works like a charm. Should be easy enough to translate to this project :)

**Comment by florisla** [comment]
This now included.

See 59cfa99b99d87bf2cb2e9176c6dfcacafb532023 (the comma bug was later fixed).

This issue can be closed.
