### ISSUE TITLE
Remove reference to "The Hitchhiker's Guide to Packaging"

### ISSUE THREAD

**Issue by supermitch** [kennethreitz/setup.py#40]
Should we point people directly to this? https://packaging.python.org/

The Hitchhiker's guide, although probably a great source of information, is outdated. Written in 2009, the last commit was in 2010.

I believe that given the state of python packaging, it is not a good reference to keep hanging around.

**Comment by florisla** [comment]
Problems:
- advises to created README.txt (not .md suffix)
- contains very minimal setup.py

Apart from that, it misses some content but is not very 'wrong' I think.

**Comment by timofurrer** [comment]
I actually agree with both of you. 

@florisla I think they've changed the README also to markdown. See: https://packaging.python.org/tutorials/packaging-projects/#creating-readme-md

As the link is in the `More Resources` section I think it's fine to add the official packaging guide proposed by @supermitch as additional resources. What do you think? See #65

**Comment by florisla** [comment]
I was referring to The Hitchiker's Guide to Python.

It has since been updated and now refers to packaging.python.org.

The latter is now thorough, complete and up to date, so there's definitely value in linking to both.
