### ISSUE TITLE
Don't encourage Python2 support :)

### ISSUE THREAD

**Issue by funkybob** [kennethreitz/setup.py#7]
It's probably better to comment out the Python2 classifiers (especially 2.6!) so you only show they're possible, rather than suggest they're desirable as a default.

**Comment by kennethreitz** [comment]
Disagree — Python 2/3 compatibility is best practice for libraries, still.

**Comment by kennethreitz** [comment]
I like the idea of commenting them out though. Will think about it.

**Comment by kennethreitz** [comment]
No.

**Comment by kennethreitz** [comment]
In 2020, yes.
